[package]
name = "pathfinder-server"
version = "0.1.0"
edition = "2021"

[dependencies]
pathfinder-core = { path = "../core" }
axum = "0.8"
tokio = { version = "1", features = ["full"] }
tower-http = { version = "0.6", features = ["fs", "cors"] }
serde_json = "1"
